name: foxi-food
region: fra
domains:
  - domain: foxi.food
    type: PRIMARY
    zone: foxi.food
services:
  # Single combined service - nginx serves React and proxies to Django
  - name: web
    dockerfile_path: Dockerfile.combined
    github:
      branch: main
      deploy_on_push: true
      repo: verteco/foxi.food
    http_port: 80
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "www.foxi.food,foxi.food,.ondigitalocean.app,localhost,127.0.0.1"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://www.foxi.food,https://foxi.food"
      - key: SECRET_KEY
        type: SECRET
        value: "your-secret-key-here"
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: REACT_APP_API_URL
        value: "https://www.foxi.food/api"
databases:
  - name: db
    engine: PG
    production: false
    version: "15"
