name: foxi-food
region: fra
domains:
  - domain: foxi.food
    type: PRIMARY
    zone: foxi.food
services:
  - name: backend
    environment_slug: python
    github:
      branch: main
      deploy_on_push: true
      repo: verteco/foxi.food
    source_dir: backend
    dockerfile_path: backend/Dockerfile
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xs
    routes:
      - path: /api
    envs:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "www.foxi.food,foxi.food,.ondigitalocean.app,localhost"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://www.foxi.food,https://foxi.food"
      - key: SECRET_KEY
        type: SECRET
        value: "your-secret-key-here"
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
    run_command: gunicorn --bind 0.0.0.0:8000 foxi_food_backend.wsgi:application
    
  - name: frontend
    environment_slug: node-js
    github:
      branch: main
      deploy_on_push: true
      repo: verteco/foxi.food
    source_dir: frontend
    dockerfile_path: frontend/Dockerfile
    http_port: 80
    instance_count: 1
    instance_size_slug: basic-xs
    envs:
      - key: REACT_APP_API_URL
        value: "https://www.foxi.food/api"
    routes:
      - path: /
databases:
  - name: db
    engine: PG
    production: false
    version: "15"
